const Images = {
  //Landing Page
  brandLogo: "/assets/images/brandLogo.svg",
  brandLogoLight: "/assets/images/brandLogoLight.svg",
  baseLessPhone: "/assets/images/baseLessPhone.png",
  heroEllipse: "/assets/images/heroEllipse.svg",
  profile_card: "/assets/images/profile_card.svg",
  team_card: "/assets/images/team_card.svg",
  create: "/assets/images/create.svg",
  search: "/assets/images/search.svg",
  target: "/assets/images/target.svg",
  join: "/assets/images/join.svg",
  vectorPhone1: "/assets/images/vectorPhone1.svg",
  vectorPhone2: "/assets/images/vectorPhone2.svg",
  bannerImg: "/assets/images/bannerImg.svg",
  football: "/assets/images/football.svg",
  google: "/assets/images/google.svg",
  facebook: "/assets/images/facebook.svg",
  darkTheme: "/assets/images/darkTheme.svg",
  emailSent: "/assets/images/emailSent.svg",
  roleDefender: "/assets/images/role-defender.svg",
  roleKeeper: "/assets/images/role-keeper.svg",
  roleStriker: "/assets/images/role-striker.svg",
  roleMidFielder: "/assets/images/role-midfielder.svg",
  roleDefenderActive: "/assets/images/role-defender-active.svg",
  roleKeeperActive: "/assets/images/role-keeper-active.svg",
  roleStrikerActive: "/assets/images/role-striker-active.svg",
  roleMidFielderActive: "/assets/images/role-midfielder-active.svg",
  goalCover: "/assets/images/goalCover.png",
  SuccessBadge: "/assets/images/SuccessBadge.svg",
  fbShare: "/assets/images/facebookShare.svg",
  twitterShare: "/assets/images/twitterShare.svg",
  whatsappShare: "/assets/images/whatsappShare.svg",
};

export default Images;
